// "https://choosealicense.com/licenses/mit/"
// const crypto = require("node:crypto")
// console.log(crypto.randomBytes(48).toString("base64url"))
// "cross-env NODE_ENV=test nyc --reporter=html mocha ./test/main.js --testTimeout=10000 --exit"

const str =
  'SELECT "WaresTickets"."wareId", "WaresTickets"."ticketId", "WaresTickets"."amount", "WaresTickets"."returned", "WaresTickets"."createdAt", "WaresTickets"."updatedAt", "ticket"."id" AS "ticket.id", "ticket"."clientId" AS "ticket.clientId", "ticket"."cost" AS "ticket.cost", "ticket"."paymentPlan" AS "ticket.paymentPlan", "ticket"."description" AS "ticket.description", "ticket"."createdAt" AS "ticket.createdAt", "ticket"."updatedAt" AS "ticket.updatedAt", (SELECT "ticket"."cost" - SUM("WaresTickets"."returned" * "ware"."unitPrice") - SUM("Transactions"."payment") FROM "WaresTickets" LEFT OUTER JOIN "Tickets" ON "WaresTickets"."ticketId" = "Tickets"."id" LEFT OUTER JOIN "Transactions" ON "Tickets"."id" = "Transactions"."ticketId" WHERE "ticketId" = "Transactions"."ticketId") AS "ticket.owed", "ware"."id" AS "ware.id", "ware"."name" AS "ware.name", "ware"."type" AS "ware.type", "ware"."tags" AS "ware.tags", "ware"."unitPrice" AS "ware.unitPrice", "ware"."createdAt" AS "ware.createdAt", "ware"."updatedAt" AS "ware.updatedAt", (SELECT "amount" - "returned" + COALESCE("WaresTickets"."returned"  - "WaresTickets"."amount", 0) FROM "OrdersWares" LEFT OUTER JOIN "Orders" ON "OrdersWares"."orderId" = "Orders"."id" WHERE "wareId" = "ware"."id" AND "Orders"."actualAt" IS NOT NULL) AS "ware.stock" FROM "WaresTickets" AS "WaresTickets" LEFT OUTER JOIN "Tickets" AS "ticket" ON "WaresTickets"."ticketId" = "ticket"."id" LEFT OUTER JOIN "Wares" AS "ware" ON "WaresTickets"."wareId" = "ware"."id" WHERE "WaresTickets"."ticketId" = \'2\' AND "WaresTickets"."wareId" = \'3\' ORDER BY "WaresTickets"."ticketId" DESC, "WaresTickets"."war'

console.log(str.slice(740))
